### ISSUE TITLE
Unknown error during Authorization: database is locked

### ISSUE THREAD

**Issue by tnttol** [vanhbakaa/Kaia-bot#6]
2024-11-07 20:21:16 | ERROR    | 101 - Angel | Unknown error during Authorization: database is locked

![image](https://github.com/user-attachments/assets/7bcb3b95-a82a-4765-83e7-9308f1a8c4ad)

**Comment by vanhbakaa** [comment]
recreate your session

**Comment by tnttol** [comment]
I recreate the session twice a day every day

bug is not fixed
